### ISSUE TITLE
Support in operator

### ISSUE THREAD

**Issue by egor045** [makhidkarun/ehex#3]
WIBNI ```if ehex(x) in list:``` were a thing

**Comment by LeamHall** [comment]
Define "thing"?

[leam@josiah ~]$ python3
Python 3.6.2 (default, Aug 25 2017, 05:10:19) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ehex.ehex import ehex
>>> mylist = [1, 2, 3]
>>> x = 2
>>> ehex(x)
2
>>> if ehex(x) in mylist:
...     print("Found it.")
... 
Found it.
>>> x = 5
>>> if ehex(x) in mylist:
...     print("Found it.")
... 
>>> 
>>>

**Comment by egor045** [comment]
```
>>> from ehex.ehex import ehex
>>> e = ehex(5)
>>> e in'35'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'in <string>' requires string as left operand, not ehex
```

List membership is OK, but ```in string``` is a nice idiom. Also kind of Pythonic.

**Comment by LeamHall** [comment]
I'm still confused. Maybe the coffee needs more time to kick in.

>>> x = 2
>>> mystring = '1234'
>>> str(ehex(x)) in mystring
True

>>> e = ehex(5)
>>> str(ehex(e)) in '12345'
True

>>> mystring = '123ABC'
>>> a = 10
>>> str(ehex(a)) in mystring
True

**Comment by LeamHall** [comment]
>>> 5 in '35'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'in <string>' requires string as left operand, not int

**Comment by egor045** [comment]
It'd be nice to do without ```str()```. May not be possible without extending str. Comes of thinking of a string as a list of characters ...

**Comment by LeamHall** [comment]
Python itself doesn't do that. While converting is nice I'd prefer it be explicit. My code needs to compare int to int and str to str without worrying about changing underneath. How would ehex know if it was supposed to provide an int or a str without being told?

**Comment by egor045** [comment]
Fair point about keeping it explicit. I'd been looking at it purely from a convenience perspective. 

There's a __contains__ method which might be overloaded to check the type of the object you're checking. The technique would be similar to how ehex does comparisons and addition/subtraction.

**Comment by egor045** [comment]
Closing this without further action. Can revisit if there's overwhelming demand for a type-agnostic in
